import styles from '@/styles/Home.module.scss'
import Nav from '@/components/nav/nav'
import React, { useEffect, useState, useRef } from 'react';
import PageCreator from '@/components/nav/pagecreator/pagecreator';


export default function Home() {

  return (
    <>
      <head>
        <title>Tesla Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <main className={styles.main}>
        <PageCreator />
      </main>
    </>
  )
}
